# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rshift_wrappers", use_symbols = TRUE, package_name = "rshift")

#' @usage NULL
#' @useDynLib rshift, .registration = TRUE
NULL

#' Calculate STARS RSI points and return to R as a vector
#' @param vals The column we are measuring change on
#' @param t_crit The critical value of a t-distribution at the desired p-value
#' @param l The cut-off length of a regime; affects sensitivity
#' @param weights The Huber weights for each data point.
rust_rodionov <- function(vals, t_crit, l, weights) .Call(wrap__rust_rodionov, vals, t_crit, l, weights)

#' Calculate STARS RSI points and return to R as a vector
#' Uses Huber weighting to handle outliers
#' @param vals The column we are measuring change on
#' @param t_crit The critical value of a t-distribution at the desired p-value
#' @param l The cut-off length of a regime; affects sensitivity
#' @param huber The tuning constant for Huber weighting.
rust_rodionov_huber <- function(vals, t_crit, l, huber) .Call(wrap__rust_rodionov_huber, vals, t_crit, l, huber)

#' Calculates the mean for each regime in a regime shift analysis.
#' @param col The column we are measuring change on.
#' @param rsi The column containing RSI values.
rust_regime_means <- function(col, rsi) .Call(wrap__rust_regime_means, col, rsi)


# nolint end
