# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rshift_wrappers", use_symbols = TRUE, package_name = "rshift")

#' @docType package
#' @usage NULL
#' @useDynLib rshift, .registration = TRUE
NULL

#' Calculate STARS RSI points and return to R as a vector
#' @export
rust_rodionov <- function(vals, t_crit, l) .Call(wrap__rust_rodionov, vals, t_crit, l)

